d /var/cache/fwupd 0755 root root - -
d /var/db/sudo 0700 root root - -
d /var/db/sudo/lectured 0700 root root - -
d /var/lib/AccountsService 0775 root root - -
d /var/lib/AccountsService/icons 0775 root root - -
d /var/lib/AccountsService/users 0700 root root - -
d /var/lib/bluetooth 0700 root root - -
d /var/lib/bluetooth/mesh 0755 root root - -
d /var/lib/color 0755 root root - -
d /var/lib/color/icc 0755 root root - -
d /var/lib/containers 0755 root root - -
d /var/lib/flatpak 0755 root root - -
d /var/lib/fwupd 0700 root root - -
d /var/lib/geoclue 0755 geoclue geoclue - -
d /var/lib/power-profiles-daemon 0755 root root - -
d /var/lib/samba 0755 root root - -
d /var/lib/samba/certs 0755 root root - -
d /var/lib/samba/lock 0755 root root - -
d /var/lib/samba/private 0700 root root - -
d /var/lib/samba/private/certs 0700 root root - -
d /var/lib/tpm2-tss 0755 root root - -
d /var/lib/tpm2-tss/system 0755 root root - -
d /var/lib/udisks2 0700 root root - -
d /var/log/samba 0700 root root - -
d /var/log/samba/old 0700 root root - -
d /var/spool/cups 0710 root lp - -
